export const CHANGE_FETCH_GOODS_LIST_PARAMS = 'CHANGE_FETCH_GOODS_LIST_PARAMS'
export const UPDATE_GOODS_LIST = 'UPDATE_GOODS_LIST'
export const UPDATE_ORDER_DETAIL = 'UPDATE_ORDER_DETAIL'
export const UPDATE_ORDER_DETAIL_INDEX_VALUE = 'UPDATE_ORDER_DETAIL_INDEX_VALUE'
